Global merge keyframes
poeschko/bs-glamor pull request #8
Opened 2017-10-19 13:16 UTC by cullophid

added bindings for global, merge, and keyframes

fixed typo in animationDuration.

2017-10-22 17:14 UTC, jeffutter requested changes

2017-10-22 17:14 UTC, jeffutter commented on README.md
> +  ("0%": [transform "scale(0.1)",  opacity "0"]),
The `;` here is supposed to be a `,` correct?

2017-10-23 15:03 UTC, jeffutter commented
Other than the small docs comment I made above. I can 👍  that this works and would love to see it merged.

2017-10-24 08:04 UTC, cullophid commented on README.md
> +  ("0%": [transform "scale(0.1)",  opacity "0"]),
It sure is

2018-02-03 17:25 UTC, merged